import AppLayout from "./Layouts/AppLayout.vue";
import BaseButton from "./components/BaseButton.vue";
import CheckBox from "./components/CheckBox.vue";
import InputError from "./components/InputError.vue";
import InputLabel from "./components/InputLabel.vue";
import InputNumber from "./components/InputNumber.vue";
import CurrencyInput from "./components/CurrencyInput.vue";
import FileInput from "./components/FileInput.vue";
import TextArea from "./components/TextArea.vue";
import TextInput from "./components/TextInput.vue";
import FormWrapper from "./components/FormWrapper.vue";
import Alert from "./components/Alert.vue";
import BreadCrumbs from "./components/BreadCrumbs.vue";
import ButtonLink from "./components/ButtonLink.vue";
import Can from "./components/Can.vue";
import Selectinput from "./components/Selectinput.vue";
import Popper from "./components/Popper.vue";
import BaseTable from "./components/BaseTable.vue";
import Tables from "./components/Tables.vue";
import RadioBox from "./components/RadioBox.vue";
import Pagination from "./components/Pagination.vue";
import InputDecimal from "./components/InputDecimal.vue";
import ButtonDeleteAll from "./components/ButtonDeleteAll.vue";
import Selects2 from "./components/Selects2.vue";
import InputQuantity from "./components/InputQuantity.vue";
import FileUpload from "./components/FileUpload.vue";
import SummernoteEditor from "./components/SummernoteEditor.vue";
import LoaderOverlay from "./components/LoaderOverlay.vue";
import Modal from "./components/Modal.vue";
import ToastNotification from "./components/ToastNotification.vue";
import SwalToast from "./components/SwalToast.vue";
import DropDown from "./components/DropDown.vue";
import QuillText from "./components/QuillText.vue";
import LoaderHorizontal from "./components/LoaderHorizontal.vue";
import InputDate from "./components/inputDate.vue";
import { VueDatePicker } from "@vuepic/vue-datepicker";
import "@vuepic/vue-datepicker/dist/main.css";
import InputTime from "./components/inputTime.vue";
import LoaderPerPage from "./components/LoaderPerPage.vue";
import InputYears from "./components/inputYears.vue";
import Callout from "./components/Callout.vue";
import FilterDynamic from "./components/FilterDynamic.vue";
import ChartBar from "./components/ChartBar.vue";
import InputWithButton from "./components/InputWithButton.vue";
import DropdownAction from "./components/DropdownAction.vue";
import Filters from "./components/Filters.vue";
import LoadingOverlay from "./components/LoadingOverlay.vue";
import ActionToolbar from "./components/ActionToolbar.vue";
export default {
    install(app) {
        app.component("loader-overlay", LoaderOverlay);
        app.component("loader-horizontal", LoaderHorizontal);
        app.component("loader-page", LoaderPerPage);
        app.component("loading-overlay", LoadingOverlay);
        app.component("alert", Alert);
        app.component("drop-down", DropDown);
        app.component("modal", Modal);
        app.component("toast-notification", ToastNotification);
        app.component("swal-toast", SwalToast);
        app.component("base-button", BaseButton);
        app.component("button-delete-all", ButtonDeleteAll);
        app.component("check-box", CheckBox);
        app.component("input-error", InputError);
        app.component("input-label", InputLabel);
        app.component("input-number", InputNumber);
        app.component("input-decimals", InputDecimal);
        app.component("input-quantity", InputQuantity);
        app.component("input-date", VueDatePicker);
        app.component("input-time", InputTime);
        app.component("input-years", InputYears);
        app.component("text-area", TextArea);
        app.component("text-input", TextInput);
        app.component("input-with-button", InputWithButton);
        app.component("quill-text", QuillText);
        app.component("callout", Callout);
        app.component("currency-input", CurrencyInput);
        app.component("file-input", FileInput);
        app.component("file-upload", FileUpload);
        app.component("form-wrapper", FormWrapper);
        app.component("app-layout", AppLayout);
        app.component("bread-crumbs", BreadCrumbs);
        app.component("button-link", ButtonLink);
        app.component("can", Can);
        app.component("select-input", Selectinput);
        app.component("select-2", Selects2);
        app.component("popper", Popper);
        app.component("tables", Tables);
        app.component("base-table", BaseTable);
        app.component("radio-box", RadioBox);
        app.component("pagination", Pagination);
        app.component("summernote-editor", SummernoteEditor);
        app.component("filter-dynamic", FilterDynamic);
        app.component("base-filters", Filters);
        app.component("chart-bar", ChartBar);
        app.component("dropdown-action", DropdownAction);
        app.component("action-toolbar", ActionToolbar);
    },
};
